FROM anapsix/alpine-java
ADD ./opendaylight-0.9.1 /opt/opendaylight-0.9.1
WORKDIR /opt/opendaylight-0.9.1
#RUN wget https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/opendaylight/0.9.1/opendaylight-0.9.1.tar.gz
