---
- name: docker 
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Install pre-requsites packages 
      apt: 
        name: "{{ packages }}" 
        state: present 
        update_cache: yes
      vars:
        packages: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python-pip

    - name: update apt url  
      raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
             | sudo apt-key add -
        
    - name: update apt repositories
      raw: grep docker /etc/apt/sources.list || add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: install docker-ce
      apt: 
        name: "{{ docker_packages }}"
        state: present 
        update_cache: yes 
      vars: 
        docker_packages: 
          - docker-ce 
          - docker-compose

    - name: install mininet docker image
      docker_container: 
        name: mininet_container
        image: iwaseyusuke/mininet
        state: started 
        expose:
          - 6655
